apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert-self
  namespace: openshift-config
spec:
  secretName: api-cert-self-secret
  commonName: "api.okd.local"
  privateKey:
    rotationPolicy: Always
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
